apiVersion: apps/v1
kind: Deployment  # 创建资源的类型是 deployment 类型
metadata:
  name: nginx-deployment # deployment 的名字
spec:
  replicas: 2     # pod 副本数量
  selector:       # deployment 资源和 pod 资源的关联方式
    matchLabels:  # 管理所有 labels=hellok8s 的 pod
      app: nginx
  template:       # 定义 pod 资源
    metadata:
      labels:     # 加上 labels 和 selector 的 matchLables 对应起来, 不需要加上 meta.name, deployment 会自动创建 pod 的 name
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx