apiVersion: apps/v1
kind: Deployment            # 创建资源的类型是 deployment 类型
metadata:
  name: hellok8s-deployment # deployment 的名字
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1           # 最大创建 4 个 pod (replicas + maxSurge)
      maxUnavailable: 1     # 最小 2 个 pod 存活 (replicas - maxUnavailable)
  replicas: 3               # pod 副本数量
  selector:                 # deployment 资源和 pod 资源的关联方式
    matchLabels:            # 管理所有 labels=hellok8s 的 pod
      app: hellok8s
  template:                 # 定义 pod 资源
    metadata:
      labels:               #|\ 加上 labels 和 selector 的 matchLables 对应起来
        app: hellok8s       #|/ 不需要加上 meta.name, deployment 会自动创建 pod 的 name
    spec:
      containers:
        - name: hellok8s-container
          image: 957360688/hellok8s:bad
          readinessProbe:   # 就绪指针, 用来获知容器合适准备好接受请求流量
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 1  # 容器启动后，Kubernetes 等待多少秒开始进行就绪检查
            successThreshold: 5     # 就绪检查成功所需的连续成功次数
            failureThreshold: 3     # 失败次数到达阈值则重启, 默认为 3
          livenessProbe:    # 存活探针用来确定什么时候需要重启容器
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
