apiVersion: v1
kind: Service
metadata:
  name: serivice-hellok8s-nodeport
spec:
  type: NodePort
  selector:
    app: hellok8s
  ports:
    - port: 3000
      nodePort: 30000       # port range is limited to 30000-32767